version: "3.10"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    entrypoint: ./docker-entrypoint.sh
    command: 
            "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000 --noreload"
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
